/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./Objects/Trees/forest_nature_set_all_in.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Tree_average_bare"
        castShadow
        receiveShadow
        geometry={nodes.Tree_average_bare.geometry}
        material={materials.AllColors_Material}
        position={[-85, - 1, -85]}
      />
      <mesh
        name="Tree_average_regular"
        castShadow
        receiveShadow
        geometry={nodes.Tree_average_regular.geometry}
        material={materials.AllColors_Material}
        position={[- 90, - 1, -60 ]}
      />
      <mesh
        name="Tree_average_lush"
        castShadow
        receiveShadow
        geometry={nodes.Tree_average_lush.geometry}
        material={materials.AllColors_Material}
        position={[-55, - 1, -85]}
      />
      <mesh
        name="Tree_small_regular"
        castShadow
        receiveShadow
        geometry={nodes.Tree_small_regular.geometry}
        material={materials.AllColors_Material}
        position={[-70, - 1, -65]}
      />
      <mesh
        name="Tree_small_bare"
        castShadow
        receiveShadow
        geometry={nodes.Tree_small_bare.geometry}
        material={materials.AllColors_Material}
        position={[-65, - 1, -75]}
      />
      <mesh
        name="Tree_Spruce_small_02"
        castShadow
        receiveShadow
        geometry={nodes.Tree_Spruce_small_02.geometry}
        material={materials.AllColors_Material}
        position={[- 77, - 1, -70]}
      />
      <mesh
        name="Tree_Spruce_tiny_01"
        castShadow
        receiveShadow
        geometry={nodes.Tree_Spruce_tiny_01.geometry}
        material={materials.AllColors_Material}
        position={[-60, - 1, -55]}
      />
      <mesh
        name="Tree_Spruce_tiny_02"
        castShadow
        receiveShadow
        geometry={nodes.Tree_Spruce_tiny_02.geometry}
        material={materials.AllColors_Material}
        position={[-82, - 1, -50]}
      />
      <mesh
        name="Tree_Spruce_small_01"
        castShadow
        receiveShadow
        geometry={nodes.Tree_Spruce_small_01.geometry}
        material={materials.AllColors_Material}
        position={[-50, - 1, -70]}
      />
      <mesh
        name="Bush_average"
        castShadow
        receiveShadow
        geometry={nodes.Bush_average.geometry}
        material={materials.AllColors_Material}
        position={[-35, - 1, -78]}
      />
      <mesh
        name="Bush_average_bare"
        castShadow
        receiveShadow
        geometry={nodes.Bush_average_bare.geometry}
        material={materials.AllColors_Material}
        position={[-58, - 1, -45 ]}
      />
      <mesh
        name="Bush_group_average"
        castShadow
        receiveShadow
        geometry={nodes.Bush_group_average.geometry}
        material={materials.AllColors_Material}
        position={[-40, - 1, -55]}
      />
      <mesh
        name="Bush_group_big"
        castShadow
        receiveShadow
        geometry={nodes.Bush_group_big.geometry}
        material={materials.AllColors_Material}
        position={[-36, - 1, -65]}
      />
      <mesh
        name="Bush_group_small"
        castShadow
        receiveShadow
        geometry={nodes.Bush_group_small.geometry}
        material={materials.AllColors_Material}
        position={[-34, - 1, -45]}
      />
      <mesh
        name="Stump_average_high"
        castShadow
        receiveShadow
        geometry={nodes.Stump_average_high.geometry}
        material={materials.AllColors_Material}
        position={[-75, - 1, -85]}
      />
      <mesh
        name="Stump_average_flat"
        castShadow
        receiveShadow
        geometry={nodes.Stump_average_flat.geometry}
        material={materials.AllColors_Material}
        position={[-80, - 1, -40]}
      />
      <mesh
        name="Stump_average_low"
        castShadow
        receiveShadow
        geometry={nodes.Stump_average_low.geometry}
        material={materials.AllColors_Material}
        position={[-84, - 1, -32]}
      />
      <mesh
        name="Stump_average_hollow"
        castShadow
        receiveShadow
        geometry={nodes.Stump_average_hollow.geometry}
        material={materials.AllColors_Material}
        position={[-73, - 1, -27]}
      />
      <mesh
        name="Log_big_regular"
        castShadow
        receiveShadow
        geometry={nodes.Log_big_regular.geometry}
        material={materials.AllColors_Material}
        position={[-53, - 1, -30]}
        rotation-y={- Math.PI * 0.5}
      />
      <mesh
        name="Log_big_knotty"
        castShadow
        receiveShadow
        geometry={nodes.Log_big_knotty.geometry}
        material={materials.AllColors_Material}
        position={[-50, - 1, -30]}
        rotation-y={- Math.PI * 0.5}
      />
      <mesh
        name="Branch_average_bare"
        castShadow
        receiveShadow
        geometry={nodes.Branch_average_bare.geometry}
        material={materials.AllColors_Material}
        position={[-70, - 1, -45]}
      />
      <mesh
        name="Branch_average_leaves"
        castShadow
        receiveShadow
        geometry={nodes.Branch_average_leaves.geometry}
        material={materials.AllColors_Material}
        position={[-63, - 1, - 30]}
      />
      <mesh
        name="Stone_average_01"
        castShadow
        receiveShadow
        geometry={nodes.Stone_average_01.geometry}
        material={materials.AllColors_Material}
        position={[-87, - 1, -10]}
      />
      <mesh
        name="Stone_average_01_mossy"
        castShadow
        receiveShadow
        geometry={nodes.Stone_average_01_mossy.geometry}
        material={materials.AllColors_Material}
        position={[-30, - 1, -83]}
      />
      <mesh
        name="Stone_group_average"
        castShadow
        receiveShadow
        geometry={nodes.Stone_group_average.geometry}
        material={materials.AllColors_Material}
        position={[-78, - 1, -20]}
      />
      <mesh
        name="Stone_group_average_mossy"
        castShadow
        receiveShadow
        geometry={nodes.Stone_group_average_mossy.geometry}
        material={materials.AllColors_Material}
        position={[-80, - 1, -78]}
      />
      <mesh
        name="Grass_bush_high_01"
        castShadow
        receiveShadow
        geometry={nodes.Grass_bush_high_01.geometry}
        material={materials.AllColors_Material}
        position={[-40, - 1, -40]}
      />
      <mesh
        name="Grass_bush_low_01"
        castShadow
        receiveShadow
        geometry={nodes.Grass_bush_low_01.geometry}
        material={materials.AllColors_Material}
        position={[-45, - 1, -50]}
      />
      <mesh
        name="Flower_bush_white"
        castShadow
        receiveShadow
        geometry={nodes.Flower_bush_white.geometry}
        material={materials.AllColors_Material}
        position={[-50, - 1, -45]}
      />
      <mesh
        name="Flower_bush_blue"
        castShadow
        receiveShadow
        geometry={nodes.Flower_bush_blue.geometry}
        material={materials.AllColors_Material}
        position={[-50, - 1, -55]}
      />
      <mesh
        name="Flower_bush_red"
        castShadow
        receiveShadow
        geometry={nodes.Flower_bush_red.geometry}
        material={materials.AllColors_Material}
        position={[-45, - 1, -42]}
      />
      <mesh
        name="Mushroom_big_brown"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_big_brown.geometry}
        material={materials.AllColors_Material}
        position={[-70, - 1, -60]}
      />
      <mesh
        name="Mushroom_big_group_brown"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_big_group_brown.geometry}
        material={materials.AllColors_Material}
        position={[-83, - 1, -60]}
      />
      <mesh
        name="Mushroom_flat_white"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_flat_white.geometry}
        material={materials.AllColors_Material}
        position={[-75, - 1, -55]}
      />
      <mesh
        name="Mushroom_flat_group_white"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_flat_group_white.geometry}
        material={materials.AllColors_Material}
        position={[-68, - 1, -38]}
      />
      <mesh
        name="Mushroom_high_yellow"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_high_yellow.geometry}
        material={materials.AllColors_Material}
        position={[-60, - 1, -35]}
      />
      <mesh
        name="Mushroom_high_group_yellow"
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_high_group_yellow.geometry}
        material={materials.AllColors_Material}
        position={[-75, - 1, -35]}
      />
    </group>
  )
}

useGLTF.preload('/forest_nature_set_all_in.glb')